version: 2
jobs:
  build:
    working_directory: /go/src/github.com/stefanwalther/docker-image-tag
    docker:
      - image: circleci/golang:1.17.5
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: make test
      - run:
          name: "CodeCov upload"
          command: bash <(curl -s https://codecov.io/bash)


